# CaveBlock Configuration ${version}
caveblock:
  command:
    # Cave Command. What command users will run to access their cave.
    # To define alias, just separate commands with white space.
    island: cave cb
    # The Cave admin command.
    # To define alias, just separate commands with white space.
    admin: cbadmin cba
world:
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: CaveBlock
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. CaveBlock-world, CaveBlock-world_nether, CaveBlock-world_end)
  world-name: caveblock-world
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: HARD
  # Radius of cave in blocks. (So distance between caves is twice this)
  # Will be rounded up to the nearest 16 blocks.
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  distance-between-caves: 64
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /cbadmin range set <player> <new range>
  # or set this permission: caveblock.island.range.<number>
  protection-range: 50
  # Start islands at these coordinates. This is where new islands will start in the
  # world. These must be a factor of your island distance, but the plugin will auto
  # calculate the closest location on the grid. Islands develop around this location
  # both positively and negatively in a square grid.
  # If none of this makes sense, leave it at 0,0.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  start-x: 0
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  start-z: 0
  offset-x: 0
  offset-z: 0
  # Cave height - Lowest is 5.
  # It is the y coordinate of the bedrock block in the schem.
  cave-height: 60
  # Use your own world generator for this world.
  # In this case, the plugin will not generate anything.
  # /!\ This feature is experimental and might not work as expected or might not work at all.
  use-own-generator: true
  # Maximum number of islands in the world. Set to -1 or 0 for unlimited.
  # If the number of islands is greater than this number, it will stop players from creating islands.
  max-islands: 0
  # The default game mode for this world. Players will be set to this mode when they create
  # a new island for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # The default biome for the overworld
  default-biome: MOUNTAINS
  # The maximum number of players a player can ban at any one time in this game mode.
  # The permission caveblock.ban.maxlimit.X where X is a number can also be used per player
  # -1 = unlimited
  ban-limit: -1
  #
  # This is cave... no height... only depth. Max 256.
  # Should not be less then island height.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  world-depth: 256
  # This indicate how many times block should be tried to generate.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  generation-tries: 2
  normal:
    #
    # Make over world roof of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    roof: true
    # Make over world floor of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    floor: true
    # Main block of which world will be generated.
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    main-block: STONE
    # Blocks that will occasionally replace main block by random chance.
    # Blocks will replace only main-block and will try to create packs that
    # are set in their strings. Chance of spawning also is required.
    # For materials first string must be MATERIAL, for entity: ENTITY.
    # Entities spawned via generator are not protected from despawing.
    # Working only with 2 high mobs currently.
    # Example:
    # MATERIAL:DIAMOND_ORE:100:5 - means there is 100% chace of spawing diamonds
    # where max amount in pack are 5 per each subchunk!
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    blocks:
      - MATERIAL:DIAMOND_ORE:1:5
      - MATERIAL:GOLD_ORE:1:4
      - MATERIAL:IRON_ORE:5:4
      - MATERIAL:COAL_ORE:10:6
      - MATERIAL:EMERALD_ORE:1:1
      - MATERIAL:CLAY:10:6
      - MATERIAL:DIRT:10:10
      - MATERIAL:GRAVEL:20:6
      - MATERIAL:GRANITE:20:10
      - MATERIAL:ANDESITE:20:10
      - MATERIAL:DIORITE:30:8
      - ENTITY:ZOMBIE:1:1
      - ENTITY:DOLPHIN:0.1:1
      - ENTITY:CAVE_SPIDER:1:1
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    # Note: Some default challenges will not be possible if there is no nether.
    # Note that with a standard nether all players arrive at the same portal and entering a
    # portal will return them back to their islands.
    generate: true
    # Islands in Nether. Change to false for standard vanilla nether.
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    islands: true
    # Nether spawn protection radius - this is the distance around the nether spawn
    # that will be protected from player interaction (breaking blocks, pouring lava etc.)
    # Minimum is 0 (not recommended), maximum is 100. Default is 25.
    # Only applies to vanilla nether
    spawn-radius: 25
    # Make over world roof of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    roof: true
    # Make over world floor of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    floor: true
    # Main block of which world will be generated.
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    main-block: NETHERRACK
    # Blocks that will occasionally replace main block by random chance.
    # Blocks will replace only main-block and will try to create packs that
    # are set in their strings. Chance of spawning also is required.
    # For materials first string must be MATERIAL, for entity: ENTITY.
    # Entities spawned via generator are not protected from despawing.
    # Working only with 2 high mobs currently.
    # Example:
    # MATERIAL:DIAMOND_ORE:100:5 - means there is 100% chace of spawing diamonds
    # where max amount in pack are 5 per each subchunk!
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    blocks:
      - MATERIAL:NETHER_QUARTZ_ORE:30:5
      - MATERIAL:SOUL_SAND:40:10
      - MATERIAL:MAGMA_BLOCK:10:3
      - MATERIAL:GLOWSTONE:20:8
      - MATERIAL:NETHER_BRICKS:10:5
      - MATERIAL:LAVA:10:1
      - ENTITY:MAGMA_CUBE:0.5:1
      - ENTITY:GHAST:0.1:1
      - ENTITY:WITHER_SKELETON:0.1:1
      - MATERIAL:FIRE:10:1
  end:
    generate: true
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    islands: true
    # /!\ This feature is experimental and might not work as expected or might not work at all.
    dragon-spawn: false
    # Make over world roof of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    roof: true
    # Make over world floor of bedrock, if false, it will be made from stone
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    floor: true
    # Main block of which world will be generated.
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    main-block: END_STONE
    # Blocks that will occasionally replace main block by random chance.
    # Blocks will replace only main-block and will try to create packs that
    # are set in their strings. Chance of spawning also is required.
    # For materials first string must be MATERIAL, for entity: ENTITY.
    # Entities spawned via generator are not protected from despawing.
    # Working only with 2 high mobs currently.
    # Example:
    # MATERIAL:DIAMOND_ORE:100:5 - means there is 100% chace of spawing diamonds
    # where max amount in pack are 5 per each subchunk!
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    blocks:
      - ENTITY:SHULKER:0.2:1
      - MATERIAL:OBSIDIAN:1:1
      - MATERIAL:CHORUS_PLANT:1:3
  # Mob white list - these mobs will NOT be removed when logging in or doing /cave
  remove-mobs-whitelist:
    - ZOMBIE_VILLAGER
    - WITHER
    - ENDERMAN
    - PIG_ZOMBIE
  # World flags. These are boolean settings for various flags for this world
  flags:
    CREEPER_DAMAGE: true
    OBSIDIAN_SCOOPING: true
    PISTON_PUSH: false
    ISLAND_RESPAWN: true
    CREEPER_GRIEFING: false
    ENDERMAN_GRIEFING: true
    CLEAN_SUPER_FLAT: false
    CHEST_DAMAGE: false
    PREVENT_TELEPORT_WHEN_FALLING: false
    ENTER_EXIT_MESSAGES: true
    ENDERMAN_DEATH_DROP: true
    OFFLINE_REDSTONE: true
    REMOVE_MOBS: true
    ENDER_CHEST: false
    ITEM_FRAME_DAMAGE: false
  # These are the default protection settings for new islands.
  # The value is the minimum island rank required allowed to do the action
  # Ranks are: Visitor = 0, Member = 900, Owner = 1000
  default-island-flags:
    HURT_ANIMALS: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    ANVIL: 500
    FISH_SCOOPING: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    FROST_WALKER: 500
    TURTLE_EGGS: 500
    COLLECT_LAVA: 500
    LEVER: 500
    RIDING: 500
    HURT_MONSTERS: 0
    NAME_TAG: 500
    ARMOR_STAND: 500
    TRADING: 0
    EGGS: 500
    ITEM_DROP: 0
    NOTE_BLOCK: 0
    NETHER_PORTAL: 500
    ITEM_PICKUP: 0
    CROP_TRAMPLE: 500
    DROPPER: 500
    BREWING: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    BEACON: 500
    TRAPDOOR: 500
    PRESSURE_PLATE: 0
    PLACE_BLOCKS: 500
    ITEM_FRAME: 500
    CRAFTING: 0
    ENCHANTING: 0
    SHEARING: 500
    SPAWN_EGGS: 500
    BED: 500
    MILKING: 0
    DISPENSER: 500
    GATE: 0
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    MOUNT_INVENTORY: 500
    BREAK_BLOCKS: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    JUKEBOX: 500
    POTION_THROWING: 500
  # These are the default settings for new islands
  default-island-settings:
    PVP_END: false
    PVP_NETHER: false
    ANIMAL_SPAWN: true
    MONSTER_SPAWN: true
    FIRE_SPREAD: true
    PVP_OVERWORLD: false
  # These settings/flags are hidden from users
  # Ops can toggle hiding in-game using SHIFT-LEFT-CLICK on flags in settings
  hidden-flags: []
  # Visitor banned commands - Visitors to islands cannot use these commands in this world
  visitor-banned-commands:
    - spawner
    - spawnmob
island:
  # Default max team size
  # Permission size cannot be less than the default below.
  max-team-size: 4
  # Default maximum number of homes a player can have. Min = 1
  # Accessed via /cave sethome <number> or /cave go <number>
  max-homes: 1
  reset:
    # How many resets a player is allowed (override with /cbadmin clearresets <player>)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 islands lifetime
    reset-limit: -1
    # Kicked or leaving players lose resets
    # Players who leave a team will lose an island reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # island by themselves and can only join a team.
    # Leave this true to avoid players exploiting free islands
    leavers-lose-reset: false
    # Allow kicked players to keep their inventory.
    # Overrides the on-leave inventory reset for kicked players.
    kicked-keep-inventory: false
    on-join:
      # What the addon should reset when the player joins or creates an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset health - if true, the player's health will be reset.
      health: true
      # Reset hunger - if true, the player's hunger will be reset.
      hunger: true
      # Reset experience points - if true, the player's experience will be reset.
      exp: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
    on-leave:
      # What the plugin should reset when the player leaves or is kicked from an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset health - if true, the player's health will be reset.
      health: false
      # Reset hunger - if true, the player's hunger will be reset.
      hunger: false
      # Reset experience - if true, the player's experience will be reset.
      exp: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
  commands:
    # List of commands to run when a player joins.
    on-join: []
    # List of commands to run when a player leaves.
    on-leave: []
  sethome:
    nether:
      allow: true
      require-confirmation: true
    the-end:
      allow: true
      require-confirmation: true
  deaths:
    # Whether deaths are counted or not.
    counted: true
    # Maximum number of deaths to count. The death count can be used by add-ons.
    max: 10
    # Reset player death count when they start a new cave or reset a cave
    reset-on-new: true
    # When a player joins a team, reset their death count
    team-join-reset: true
protection:
  # Geo restrict mobs.
  # Mobs that exit the island space where they were spawned will be removed.
  geo-limit-settings:
    - GHAST
    - BAT
    - BLAZE
  # Invincible visitors. List of damages that will not affect visitors.
  # Make list blank if visitors should receive all damages
  invincible-visitors:
    - BLOCK_EXPLOSION
    - CONTACT
    - CUSTOM
    - DROWNING
    - ENTITY_ATTACK
    - ENTITY_EXPLOSION
    - FALL
    - FALLING_BLOCK
    - FIRE
    - FIRE_TICK
    - LAVA
    - LIGHTNING
    - MAGIC
    - POISON
    - PROJECTILE
    - STARVATION
    - SUFFOCATION
    - THORNS
    - WITHER
    - DRAGON_BREATH
    - FLY_INTO_WALL
    - HOT_FLOOR
    - CRAMMING
    - VOID
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
debug: false
